### ISSUE TITLE
Get ready for the first crash report.

### ISSUE THREAD

**Issue by border999** [MoePus/Flerovium#1]
https://gist.github.com/border999/75ee4b031bfaef02394ceb6f0897d7b5
I crafted a storage upgrade for a sophisticated storage barrel and crashed within a few seconds of it appearing in my hand. If I threw this in the wrong spot or to the wrong mod I appologize.
This will probably be a learning experience for both of us if you find anything interesting in that crash report.
![Screenshot (13)](https://github.com/user-attachments/assets/53625589-37be-408b-9d84-c3a4f35e68d4)
Edit: Managed to select a different item before I crashed when getting back into my world. Here's a picture highlighing the item I had in my hand that seems to be the trigger.

**Comment by MoePus** [comment]
Should be fixed in 1.0.2

**Comment by border999** [comment]
will reopen if issue persists. Test update tomorrow..
