### ISSUE TITLE
Crash with Oculus 1.8.0

### ISSUE THREAD

**Issue by masonclomid** [MoePus/Flerovium#10]
https://gist.github.com/masonclomid/c27abc6046afbf5091ab362b060a7c55
Even though it's a messy pack, the only change that caused the crash was the Oculus update.

**Comment by MoePus** [comment]
Some mod breaks Embeddium's Mixin.
I dont know what mod did it, but
try remove palladium mod and see if this crash still exists.

**Comment by masonclomid** [comment]
Exact same crash :(
And the crash will not occur unless Flerovium and Oculus1.8.0 coexist. Is it possible that it has something to do with oculus' fix for Mekanism, also my crash helper mentioned the mod betterchunkloading-1.20.1-5.2.

**Comment by MoePus** [comment]
Thats strange, flerovium should work fine with oculus 1.8 (And it works fine on my 170 mods modpack with sinytra connector)
Could you please also upload your lastest.log in logs folder?

**Comment by masonclomid** [comment]
https://gist.github.com/masonclomid/f003193cbbbadc1d99683df4dcd68b04
A new one, I also deleted some suspicious mods.

**Comment by MoePus** [comment]
Find it, its [bendy-lib](https://github.com/KosmX/bendy-lib) 
...
It cannot be compatible with Flerovium. I have to mark it incompatible or disable some optimizations when it is installed

**Comment by masonclomid** [comment]
Thanks for all your hard work, that would be great if so. bendy lib is actually a legacy optional dependency of playeranimator, but given that playeranimator and its users are increasingly focusing on the no-bend style, bendy lib is almost useless except for Emotecraft.
Which may not require further action, I will close the issue after confirming it. Thank you again for creating such a nice mod!
