### ISSUE TITLE
Equipped/Held Items Are Glitched in the Inventory View

### ISSUE THREAD

**Issue by CraftyZombie** [MoePus/Flerovium#5]
I don't really know how to explain this without just showing screenshots.

Without Flerovium:
<img width="151" alt="Screen Shot 2024-11-30 at 8 56 32 PM" src="https://github.com/user-attachments/assets/123608ba-8fc9-4fb1-878c-0dadbb03093e">

With Flerovium:
<img width="221" alt="Screen Shot 2024-11-30 at 9 00 43 PM" src="https://github.com/user-attachments/assets/ade4ab56-0553-45fa-be65-881fe8a41dc6">
<img width="220" alt="Screen Shot 2024-11-30 at 9 00 36 PM" src="https://github.com/user-attachments/assets/c0f92cea-110d-49a9-b23f-bb5ac8a41fe8">

**Comment by MoePus** [comment]
fixed in 1.1.1

**Comment by CraftyZombie** [comment]
Thank you!

**Comment by CraftyZombie** [comment]
Shoot, there are still some issues.
<img width="109" alt="Screen Shot 2024-12-01 at 11 14 50 AM" src="https://github.com/user-attachments/assets/a9e5d20c-d57c-41bc-ad3b-60b3b29c309d">

**Comment by CraftyZombie** [comment]
Nevermind, I made a mistake and ended up with the old version again.
Please disregard.
