### ISSUE TITLE
[1.1.1] Flerovium cause Obscure Tooltips's visual broken

### ISSUE THREAD

**Issue by yuusyaasisutanto** [MoePus/Flerovium#7]
confirmed in minimal configuration with mekanism mods
(I tested obscure tooltips + mekanism only, but caused freerunner visual broken, so flerovium isn't cause about that)
https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips

(Vanilla Sword)
![image](https://github.com/user-attachments/assets/fd01fa80-3662-4de5-a0ff-1b2451aba721)
Disabled Flerovium
![image](https://github.com/user-attachments/assets/28d1b10c-5558-4666-81c0-73e269412981)

**Comment by MoePus** [comment]
fixed in 1.1.2

**Comment by yuusyaasisutanto** [comment]
just confirmed completely fixed!
thanks for working hard, I'm respecting you
